INSERT INTO PRODUTO_ENTITY
(NOME, VALOR_SEM_DESCONTO, TIPO_PRODUTO, PESO_KG, PESO_MB, VALOR_FRETE, PROMOCAO, VALOR_COM_DESCONTO, VALOR_TOTAL_COM_FRETE)
VALUES
('televisao', 1000, 'DIGITAL', 10, 0, 0, TRUE, 0, 0),
('MACACO', 1000, 'DIGITAL', 10, 0, 0, FALSE, 0, 0),
('televisao', 1000, 'DIGITAL', 10, 0, 0, TRUE, 0, 0);
