CREATE TABLE PRODUTO_ENTITY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    VALOR_SEM_DESCONTO BIGINT,
    TIPO_PRODUTO ENUM('FISICO', 'DIGITAL'),
    PESO_KG BIGINT,
    PESO_MB BIGINT,
    VALOR_FRETE BIGINT,
    PROMOCAO BOOLEAN,
    VALOR_COM_DESCONTO BIGINT,
    VALOR_TOTAL_COM_FRETE BIGINT
);