CREATE TABLE PRODUTO_ENTITY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    VALOR_SEM_DESCONTO DECIMAL(10, 2),
    TIPO_PRODUTO VARCHAR(30),
    PESO_KG DECIMAL(10, 2),
    TAMANHO_MB DECIMAL(10, 2),
    VALOR_FRETE DECIMAL(10, 2),
    PROMOCAO BOOLEAN,
    VALOR_COM_DESCONTO DECIMAL(10, 2),
    VALOR_TOTAL_COM_FRETE DECIMAL(10, 2)
);